language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - ./travis.sh

env:
  matrix:
    - RUN_ITS=false
    - RUN_ITS=true SQ_VERSION=LTS
    - RUN_ITS=true SQ_VERSION=5.1.2
    - RUN_ITS=true SQ_VERSION=DEV

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

before_cache:
  - rm -rf $HOME/.m2/repository/org/codehaus/mojo/sonar-maven-plugin

notifications:
  email: false
