language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - ./travis.sh

env:
  matrix:
    - TARGET=CI
    - TARGET=IT SQ_VERSION=LTS MAVEN_VERSION=2.2.1
    - TARGET=IT SQ_VERSION=LTS MAVEN_VERSION=3.0.5
# 5.1 is the latest version with design feature
    - TARGET=IT SQ_VERSION=5.1.2 MAVEN_VERSION=3.1.1
    - TARGET=IT SQ_VERSION=5.2 MAVEN_VERSION=3.2.5
    - TARGET=IT SQ_VERSION=DEV MAVEN_VERSION=3.3.9

cache:
  directories:
    - '$HOME/.m2/repository'

before_cache:
  - rm -rf $HOME/.m2/repository/org/codehaus/mojo/sonar-maven-plugin

notifications:
  email: false
